version: '3.8'

services:
  evaluation_service:
    build:
      context: evaluation-propriete-service/
      dockerfile: ./Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URI=postgresql://eval_user:eval_password@eval_prop_db/eval_prop_db
    networks:
      - network1

  eval_prop_db:
    image: postgres:12.1-alpine
    container_name: eval_prop_db
    volumes:
      - postgres_data_eval:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eval_user
      - POSTGRES_PASSWORD=eval_password
      - POSTGRES_DB=eval_prop_db
    networks:
      - network1


  solvabilite_service:
    build:
      context: solvabilite-service/
      dockerfile: ./Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URI=postgresql://solvabilite_user:solvabilite_password@solvabilite_db/solvabilite_db
    networks:
      - network1

  solvabilite_db:
    image: postgres:12.1-alpine
    container_name: solvabilite_db
    volumes:
      - postgres_data_solvabilite:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=solvabilite_user
      - POSTGRES_PASSWORD=solvabilite_password
      - POSTGRES_DB=solvabilite_db
    networks:
      - network1

  service-extraction:
    build:
      context: extraction-informations-service/
      dockerfile: ./Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - ./.env
    networks:
      - network1
    
  service-composite:
    build:
      context: service-composite/
      dockerfile: ./Dockerfile
    ports:
      - "8004:8000"
    environment:
      - EVALUATION_SERVICE_URL=http://evaluation_service:8001
      - SOLVABILITE_SERVICE_URL=http://solvabilite_service:8002
      - EXTRACTION_SERVICE_URL=http://service-extraction:8003
    networks:
      - network1
    

volumes:
  postgres_data_solvabilite:
  postgres_data_eval:

networks:
  network1:
    driver: bridge

